begin;

create schema if not exists app;

create or replace function app.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table public.companies (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null,
  description text,
  contact_email text,
  contact_phone text,
  time_zone text not null default 'America/Guatemala',
  is_enabled boolean not null default true,
  flow_key text,
  notification_mode text not null default 'disabled' check (notification_mode in ('disabled','always','outside_business_hours')),
  notification_recipients text[] not null default '{}',
  business_hours_start time,
  business_hours_end time,
  business_days smallint[] not null default '{1,2,3,4,5}',
  whatsapp_bot_mode text not null default 'visual' check (whatsapp_bot_mode in ('disabled','visual','ai')),
  agent_farewell_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  constraint companies_code_key unique (code),
  constraint companies_farewell_length check (agent_farewell_message is null or length(agent_farewell_message) <= 1000)
);

create table public.profiles (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  name text not null,
  role text not null check (role in ('admin','agent')),
  created_at timestamptz not null default now(),
  unique (company_id, id),
  unique (company_id, role)
);

create table public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  company_id bigint references public.companies(id) on delete restrict,
  profile_id bigint,
  legacy_profile_id bigint,
  name text not null,
  email text not null,
  phone text,
  role text not null check (role in ('super_admin','admin','agent')),
  status boolean not null default true,
  contact_id bigint,
  last_login timestamptz,
  last_activity timestamptz,
  is_online boolean not null default false,
  avatar_mime_type text,
  avatar_file_name text,
  avatar_updated_at timestamptz,
  conversation_count integer not null default 0 check (conversation_count >= 0),
  password_migration_status text not null default 'reset_required' check (password_migration_status in ('reset_required','invited','completed','disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  constraint users_role_company check (
    (role = 'super_admin' and company_id is null) or
    (role <> 'super_admin' and company_id is not null)
  ),
  constraint users_profile_fk foreign key (company_id, profile_id) references public.profiles(company_id, id) on delete restrict,
  unique (company_id, id)
);

create unique index users_company_email_key on public.users (coalesce(company_id, 0), lower(email));
create index users_auth_user_idx on public.users(auth_user_id) where auth_user_id is not null;

create table public.contacts (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  name text,
  phone_number text not null,
  country text,
  status text not null default 'active' check (status in ('new','active','blocked','archived')),
  welcome_sent boolean not null default false,
  last_message_at timestamptz,
  last_location_latitude double precision,
  last_location_longitude double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  unique (company_id, id),
  unique (company_id, phone_number),
  constraint contacts_latitude_check check (last_location_latitude is null or last_location_latitude between -90 and 90),
  constraint contacts_longitude_check check (last_location_longitude is null or last_location_longitude between -180 and 180)
);

alter table public.users
  add constraint users_contact_fk foreign key (company_id, contact_id)
  references public.contacts(company_id, id) on delete set null;

create table public.conversations (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  contact_id bigint not null,
  channel text not null check (channel in ('whatsapp','webchat')),
  external_thread_key text,
  status text not null default 'open' check (status in ('open','waiting','closed')),
  greeting_sent boolean not null default false,
  total_messages integer not null default 0 check (total_messages >= 0),
  ai_messages integer not null default 0 check (ai_messages >= 0),
  first_response_seconds integer check (first_response_seconds is null or first_response_seconds >= 0),
  rating smallint check (rating is null or rating between 1 and 5),
  assigned_user_id bigint,
  assigned_at timestamptz,
  assigned_by_user_id bigint,
  closed_by_user_id bigint,
  agent_requested_at timestamptz,
  last_agent_alert_email_at timestamptz,
  started_at timestamptz not null default now(),
  last_activity_at timestamptz,
  ended_at timestamptz,
  updated_at timestamptz,
  unique (company_id, id),
  constraint conversations_contact_fk foreign key (company_id, contact_id) references public.contacts(company_id, id) on delete restrict,
  constraint conversations_assigned_user_fk foreign key (company_id, assigned_user_id) references public.users(company_id, id) on delete set null,
  constraint conversations_assigned_by_fk foreign key (company_id, assigned_by_user_id) references public.users(company_id, id) on delete set null,
  constraint conversations_closed_by_fk foreign key (company_id, closed_by_user_id) references public.users(company_id, id) on delete set null,
  constraint conversations_end_check check (ended_at is null or ended_at >= started_at)
);

create unique index conversations_open_channel_key
  on public.conversations(company_id, contact_id, channel)
  where status <> 'closed';
create index conversations_inbox_idx on public.conversations(company_id, status, assigned_user_id, last_activity_at desc);

create table public.messages (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  conversation_id bigint not null,
  contact_id bigint not null,
  sender text not null check (sender in ('contact','agent','bot','ai','system')),
  message text,
  type text not null check (type in ('text','image','document','audio','location','template','options','question','transfer','system')),
  channel text not null check (channel in ('whatsapp','webchat')),
  external_message_id text,
  latitude numeric(9,6),
  longitude numeric(9,6),
  location_name text,
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (company_id, id),
  constraint messages_conversation_fk foreign key (company_id, conversation_id) references public.conversations(company_id, id) on delete cascade,
  constraint messages_contact_fk foreign key (company_id, contact_id) references public.contacts(company_id, id) on delete restrict,
  constraint messages_location_check check (
    (latitude is null and longitude is null) or
    (latitude between -90 and 90 and longitude between -180 and 180)
  )
);

create unique index messages_external_key on public.messages(company_id, external_message_id) where external_message_id is not null;
create index messages_conversation_sent_idx on public.messages(company_id, conversation_id, sent_at, id);

create table public.attachments (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  message_id bigint not null,
  file_name text not null,
  mime_type text not null,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  storage_bucket text not null default 'chat-attachments',
  storage_path text not null,
  sha256 text,
  whatsapp_media_id text,
  uploaded_at timestamptz not null default now(),
  unique (company_id, id),
  unique (storage_bucket, storage_path),
  constraint attachments_message_fk foreign key (company_id, message_id) references public.messages(company_id, id) on delete cascade
);
create unique index attachments_whatsapp_media_key on public.attachments(company_id, whatsapp_media_id) where whatsapp_media_id is not null;

create table public.integrations (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  provider text not null check (provider in ('whatsapp_cloud','email','webhook')),
  phone_number_id text,
  waba_id text,
  app_id text,
  app_secret_ciphertext text,
  access_token_ciphertext text,
  verify_token_hash text,
  api_base_url text not null default 'https://graph.facebook.com',
  api_version text not null default 'v23.0',
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  unique (company_id, id),
  unique (provider, phone_number_id)
);

create table public.whatsapp_templates (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  name text not null,
  language text not null,
  template_identifier text,
  body_param_count integer not null default 0 check (body_param_count >= 0),
  is_active boolean not null default true,
  meta_status text,
  meta_category text,
  meta_header_format text,
  meta_header_param_count integer not null default 0 check (meta_header_param_count >= 0),
  meta_button_count integer not null default 0 check (meta_button_count >= 0),
  meta_components jsonb not null default '[]'::jsonb check (jsonb_typeof(meta_components) = 'array'),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  unique (company_id, id),
  unique (company_id, name, language)
);

create table public.received_messages (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  integration_id bigint not null,
  message_meta_id text not null,
  status text not null default 'received' check (status in ('received','processing','processed','failed')),
  payload jsonb not null,
  error_message text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  unique (company_id, id),
  unique (integration_id, message_meta_id),
  constraint received_integration_fk foreign key (company_id, integration_id) references public.integrations(company_id, id) on delete cascade
);

create table public.outbox_messages (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  integration_id bigint not null,
  conversation_id bigint,
  idempotency_key text not null,
  phone_number_id text,
  recipient text not null,
  type text not null,
  content jsonb not null,
  status text not null default 'pending' check (status in ('pending','processing','sent','failed','dead_letter')),
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz,
  message_meta_id text,
  error_code text,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  sent_at timestamptz,
  unique (company_id, id),
  unique (company_id, idempotency_key),
  constraint outbox_integration_fk foreign key (company_id, integration_id) references public.integrations(company_id, id) on delete restrict,
  constraint outbox_conversation_fk foreign key (company_id, conversation_id) references public.conversations(company_id, id) on delete set null
);
create index outbox_due_idx on public.outbox_messages(status, next_attempt_at, created_at) where status in ('pending','failed');

create table public.bot_settings (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  name text not null,
  configuration jsonb not null default '{}'::jsonb check (jsonb_typeof(configuration) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  unique (company_id, id),
  unique (company_id, name)
);

create table public.whatsapp_bot_flows (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  name text not null,
  description text,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  is_active boolean not null default false,
  builder jsonb not null default '{"nodes":[],"edges":[]}'::jsonb check (jsonb_typeof(builder) = 'object'),
  published jsonb check (published is null or jsonb_typeof(published) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  published_at timestamptz,
  unique (company_id, id),
  unique (company_id, name)
);

create unique index whatsapp_active_flow_key on public.whatsapp_bot_flows(company_id) where is_active;

create table public.whatsapp_bot_execution_states (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  conversation_id bigint not null,
  flow_id bigint not null,
  current_node_id text,
  status text not null default 'active' check (status in ('active','waiting','completed','failed','cancelled')),
  variables jsonb not null default '{}'::jsonb check (jsonb_typeof(variables) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  last_input_at timestamptz,
  unique (company_id, id),
  unique (company_id, conversation_id),
  constraint whatsapp_state_conversation_fk foreign key (company_id, conversation_id) references public.conversations(company_id, id) on delete cascade,
  constraint whatsapp_state_flow_fk foreign key (company_id, flow_id) references public.whatsapp_bot_flows(company_id, id) on delete cascade
);

create table public.webchatbot_flows (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  name text not null,
  description text,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  is_active boolean not null default false,
  builder jsonb not null default '{"nodes":[],"edges":[]}'::jsonb check (jsonb_typeof(builder) = 'object'),
  published jsonb check (published is null or jsonb_typeof(published) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  published_at timestamptz,
  unique (company_id, id),
  unique (company_id, name)
);

create table public.webchatbot_widgets (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  name text not null,
  is_active boolean not null default true,
  active_flow_id bigint,
  primary_color text not null default '#e8782e',
  accent_color text not null default '#b45309',
  background_color text not null default '#ffffff',
  text_color text not null default '#1c1917',
  font_family text not null default 'Inter, system-ui, sans-serif',
  position text not null default 'bottom-right' check (position in ('bottom-left','bottom-right')),
  header_title text not null default '¿Cómo podemos ayudarte?',
  welcome_text text not null default 'Hola, estamos para ayudarte.',
  placeholder_text text not null default 'Escribe tu mensaje…',
  bubble_text text not null default 'Ayuda',
  brand_text text not null default 'Grupo Movensa',
  show_branding boolean not null default true,
  allow_free_text boolean not null default true,
  allow_live_chat boolean not null default true,
  border_radius integer not null default 16 check (border_radius between 0 and 32),
  launcher_icon text,
  content jsonb not null default '{"sections":{"home":true,"conversation":true,"faqs":true,"articles":true},"quickLinks":[],"faqCategories":[],"articleCategories":[]}'::jsonb check (jsonb_typeof(content) = 'object'),
  conversation_empty_image text,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  unique (company_id, id),
  unique (company_id, name),
  constraint widget_active_flow_fk foreign key (company_id, active_flow_id) references public.webchatbot_flows(company_id, id) on delete set null
);

create table public.webchatbot_installation_keys (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  widget_id bigint not null,
  name text not null,
  install_type text not null check (install_type in ('script','wordpress')),
  activation_key_hash text not null,
  activation_key_prefix text not null,
  allowed_domains text[] not null default '{}',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  unique (company_id, id),
  unique (activation_key_hash),
  constraint webchat_key_widget_fk foreign key (company_id, widget_id) references public.webchatbot_widgets(company_id, id) on delete cascade
);

create table public.webchatbot_sessions (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  widget_id bigint not null,
  installation_key_id bigint not null,
  flow_id bigint,
  public_session_key_hash text not null,
  public_session_key_prefix text not null,
  origin_domain text,
  page_url text,
  referrer_url text,
  visitor_name text,
  visitor_email text,
  visitor_phone text,
  status text not null default 'active' check (status in ('active','waiting_agent','live','closed','expired')),
  current_node_key text,
  live_chat_requested boolean not null default false,
  live_chat_requested_at timestamptz,
  live_chat_conversation_id bigint,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  started_at timestamptz not null default now(),
  last_activity_at timestamptz,
  ended_at timestamptz,
  unique (company_id, id),
  unique (public_session_key_hash),
  constraint session_widget_fk foreign key (company_id, widget_id) references public.webchatbot_widgets(company_id, id) on delete restrict,
  constraint session_installation_fk foreign key (company_id, installation_key_id) references public.webchatbot_installation_keys(company_id, id) on delete restrict,
  constraint session_flow_fk foreign key (company_id, flow_id) references public.webchatbot_flows(company_id, id) on delete set null,
  constraint session_conversation_fk foreign key (company_id, live_chat_conversation_id) references public.conversations(company_id, id) on delete set null
);

create index webchat_session_poll_idx on public.webchatbot_sessions(company_id, status, last_activity_at desc);

create table public.webchatbot_messages (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  session_id bigint not null,
  conversation_id bigint,
  sender text not null check (sender in ('visitor','agent','bot','ai','system')),
  client_message_id text,
  message_type text not null check (message_type in ('text','options','question','transfer','image','document','audio','location','template','system')),
  content text,
  payload jsonb,
  created_at timestamptz not null default now(),
  unique (company_id, id),
  unique (session_id, client_message_id),
  constraint webchat_message_session_fk foreign key (company_id, session_id) references public.webchatbot_sessions(company_id, id) on delete cascade,
  constraint webchat_message_conversation_fk foreign key (company_id, conversation_id) references public.conversations(company_id, id) on delete set null
);

create index webchat_message_poll_idx on public.webchatbot_messages(company_id, session_id, id);

create table public.webchatbot_events (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  session_id bigint,
  conversation_id bigint,
  channel text not null default 'webchat',
  event_type text not null,
  node_key text,
  label text,
  value text,
  metadata jsonb,
  created_at timestamptz not null default now(),
  unique (company_id, id),
  constraint webchat_event_session_fk foreign key (company_id, session_id) references public.webchatbot_sessions(company_id, id) on delete cascade,
  constraint webchat_event_conversation_fk foreign key (company_id, conversation_id) references public.conversations(company_id, id) on delete set null
);

create table public.company_ai_settings (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  is_enabled boolean not null default false,
  provider text not null default 'openai' check (provider in ('openai','deepseek','gemini')),
  model text not null default 'gpt-4.1-mini',
  api_key_ciphertext text,
  api_base_url text,
  response_mode text not null default 'outside_business_hours' check (response_mode in ('disabled','always','outside_business_hours','unassigned_only')),
  system_prompt text,
  fallback_message text,
  temperature numeric(4,2) not null default 0.30 check (temperature between 0 and 2),
  max_tokens integer not null default 500 check (max_tokens between 1 and 8000),
  daily_message_limit integer check (daily_message_limit is null or daily_message_limit > 0),
  monthly_message_limit integer check (monthly_message_limit is null or monthly_message_limit > 0),
  pause_when_assigned boolean not null default true,
  escalate_on_human_request boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  last_tested_at timestamptz,
  last_test_success boolean,
  last_test_message text,
  unique (company_id),
  unique (company_id, id)
);

create table public.company_ai_knowledge_items (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  title text not null,
  category text,
  content text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  unique (company_id, id)
);

create table public.ai_usage_logs (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  conversation_id bigint,
  message_id bigint,
  provider text not null,
  model text not null,
  prompt_tokens integer not null default 0 check (prompt_tokens >= 0),
  completion_tokens integer not null default 0 check (completion_tokens >= 0),
  total_tokens integer not null default 0 check (total_tokens >= 0),
  estimated_cost_usd numeric(18,8),
  success boolean not null default false,
  error_code text,
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  reason text,
  created_at timestamptz not null default now(),
  unique (company_id, id),
  constraint ai_usage_conversation_fk foreign key (company_id, conversation_id) references public.conversations(company_id, id) on delete set null,
  constraint ai_usage_message_fk foreign key (company_id, message_id) references public.messages(company_id, id) on delete set null
);
create index ai_usage_period_idx on public.ai_usage_logs(company_id, created_at desc);

create table public.ai_conversation_logs (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  conversation_id bigint not null,
  inbound_message_id bigint,
  outbound_message_id bigint,
  provider text,
  model text,
  response_mode text,
  decision text not null,
  prompt_excerpt text,
  response_text text,
  success boolean not null default false,
  escalated_to_human boolean not null default false,
  error_code text,
  created_at timestamptz not null default now(),
  unique (company_id, id),
  constraint ai_log_conversation_fk foreign key (company_id, conversation_id) references public.conversations(company_id, id) on delete cascade,
  constraint ai_log_inbound_fk foreign key (company_id, inbound_message_id) references public.messages(company_id, id) on delete set null,
  constraint ai_log_outbound_fk foreign key (company_id, outbound_message_id) references public.messages(company_id, id) on delete set null
);
create index ai_conversation_log_idx on public.ai_conversation_logs(company_id, conversation_id, created_at desc);

create table public.company_admin_audits (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  action text not null,
  detail jsonb,
  actor_user_id bigint,
  actor_name text,
  actor_email text,
  actor_role text,
  request_id uuid,
  ip_address inet,
  created_at timestamptz not null default now(),
  unique (company_id, id),
  constraint audit_actor_fk foreign key (company_id, actor_user_id) references public.users(company_id, id) on delete set null
);

create table public.company_whatsapp_events (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  event_type text not null,
  source text,
  success boolean not null,
  template_name text,
  language text,
  to_phone_masked text,
  phone_number_id text,
  summary text not null,
  detail jsonb,
  created_at timestamptz not null default now(),
  unique (company_id, id)
);

create table public.user_session_events (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  company_id bigint references public.companies(id) on delete cascade,
  role text,
  event_type text not null,
  success boolean not null,
  user_name text,
  email text,
  ip_address inet,
  detail jsonb,
  created_at timestamptz not null default now(),
  unique (company_id, id)
);

create table public.data_retention_policies (
  company_id bigint primary key references public.companies(id) on delete cascade,
  message_days integer not null default 730 check (message_days between 30 and 3650),
  attachment_days integer not null default 730 check (attachment_days between 30 and 3650),
  session_days integer not null default 365 check (session_days between 30 and 3650),
  audit_days integer not null default 730 check (audit_days between 90 and 3650),
  ai_log_days integer not null default 180 check (ai_log_days between 30 and 3650),
  updated_at timestamptz not null default now()
);

create trigger companies_updated_at before update on public.companies for each row execute function app.set_updated_at();
create trigger users_updated_at before update on public.users for each row execute function app.set_updated_at();
create trigger contacts_updated_at before update on public.contacts for each row execute function app.set_updated_at();
create trigger conversations_updated_at before update on public.conversations for each row execute function app.set_updated_at();
create trigger integrations_updated_at before update on public.integrations for each row execute function app.set_updated_at();
create trigger templates_updated_at before update on public.whatsapp_templates for each row execute function app.set_updated_at();
create trigger bot_settings_updated_at before update on public.bot_settings for each row execute function app.set_updated_at();
create trigger whatsapp_flows_updated_at before update on public.whatsapp_bot_flows for each row execute function app.set_updated_at();
create trigger whatsapp_states_updated_at before update on public.whatsapp_bot_execution_states for each row execute function app.set_updated_at();
create trigger webchat_flows_updated_at before update on public.webchatbot_flows for each row execute function app.set_updated_at();
create trigger webchat_widgets_updated_at before update on public.webchatbot_widgets for each row execute function app.set_updated_at();
create trigger ai_settings_updated_at before update on public.company_ai_settings for each row execute function app.set_updated_at();
create trigger ai_knowledge_updated_at before update on public.company_ai_knowledge_items for each row execute function app.set_updated_at();
create trigger outbox_updated_at before update on public.outbox_messages for each row execute function app.set_updated_at();

commit;
