begin;

create table public.automation_jobs (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  conversation_id bigint not null,
  inbound_message_id bigint,
  kind text not null check (kind in ('ai_response','media_download','session_close')),
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending','processing','completed','failed','dead_letter')),
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  locked_by text,
  error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  unique (company_id, id),
  constraint automation_conversation_fk foreign key (company_id, conversation_id) references public.conversations(company_id, id) on delete cascade,
  constraint automation_message_fk foreign key (company_id, inbound_message_id) references public.messages(company_id, id) on delete set null
);

create unique index automation_job_once_idx on public.automation_jobs(kind, inbound_message_id) where inbound_message_id is not null;
create index automation_job_due_idx on public.automation_jobs(status, next_attempt_at, created_at) where status in ('pending','failed');
create trigger automation_jobs_updated_at before update on public.automation_jobs for each row execute function app.set_updated_at();

alter table public.automation_jobs enable row level security;
alter table public.automation_jobs force row level security;
create policy automation_jobs_admin_read on public.automation_jobs for select to authenticated
  using (app.is_company_admin(company_id));
revoke all on public.automation_jobs from anon, authenticated;
grant select on public.automation_jobs to authenticated;

commit;
